# Generated by Django 5.0.2 on 2025-03-15 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cryptocurrency_coin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('crypto_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'Portfolio History',
                'ordering': ['-date'],
            },
        ),
    ]
