# Generated by Django 5.0.2 on 2025-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliohistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
